services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "5415"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ecommerce_backend
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      CORS_ALLOW_ALL_ORIGINS: "1"
      DB_ENGINE: "django.db.backends.postgresql"
      POSTGRES_DB: "ecommerce_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5415"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backend_media:/app/backend/media

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    container_name: ecommerce_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_media:
