# Generated by Django 4.2 on 2026-05-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_workflow_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('кп', 'Коммерческое предложение'), ('счёт', 'Счёт'), ('акт', 'Акт'), ('накладная', 'Накладная')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('кп', 'Коммерческое предложение'), ('счёт', 'Счёт'), ('акт', 'Акт'), ('накладная', 'Накладная')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
