# Generated by Django 4.2 on 2026-05-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_actionlog'),
    ]

    def _seed_roles_and_migrate_user_role(apps, schema_editor):
        Role = apps.get_model("users", "Role")
        User = apps.get_model("users", "User")

        role_map = {
            "client": {"name": "client", "description": "Client"},
            "manager": {"name": "manager", "description": "Manager"},
            "admin": {"name": "admin", "description": "Admin"},
        }

        roles = {}
        for key, payload in role_map.items():
            role, _ = Role.objects.get_or_create(
                name=payload["name"],
                defaults={"description": payload["description"]},
            )
            roles[key] = role

        # Переносим существующее строковое поле role -> FK role_id
        for user in User.objects.all().only("id", "role"):
            # user.role здесь ещё строка (до AlterField на БД)
            role_key = getattr(user, "role", None) or "client"
            role_obj = roles.get(role_key, roles["client"])
            User.objects.filter(id=user.id).update(role_id=role_obj.id)

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.RunPython(_seed_roles_and_migrate_user_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
    ]
