# Generated by ChatGPT on 2026-05-07

from django.db import migrations


def seed_roles_and_fill_user_role(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")

    role_map = {
        "client": {"name": "client", "description": "Client"},
        "manager": {"name": "manager", "description": "Manager"},
        "admin": {"name": "admin", "description": "Admin"},
    }

    roles = {}
    for key, payload in role_map.items():
        role, _ = Role.objects.get_or_create(
            name=payload["name"],
            defaults={"description": payload["description"]},
        )
        roles[key] = role

    # Если в БД уже есть пользователи с NULL role, проставляем client.
    User.objects.filter(role__isnull=True).update(role_id=roles["client"].id)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_role_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_fill_user_role, migrations.RunPython.noop),
    ]

